[env:esp32dev]
platform = espressif32
# board = esp32-c3-devkitm-1
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -I include

lib_deps =
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git
    bblanchon/ArduinoJson @ ^6.21.3
    ropg/ezTime @ ^0.8.3
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    jandrassy/TelnetStream @ ^1.2.5
    