[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
    https://github.com/witnessmenow/Universal-Arduino-Telegram-Bot.git
    bblanchon/ArduinoJson @ ^6.21.3
    arduino-libraries/NTPClient @ ^3.2.1
    ropg/ezTime @ ^0.8.3